staging-settings:
  user-workflow:
    workflow-name: "wraith-market-suggester-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../../secrets.yaml"

production-settings:
  user-workflow:
    workflow-name: "wraith-market-suggester"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../../secrets.yaml"
